// Code generated by "stringer -type=ChainHandledState"; DO NOT EDIT.

package shared

import "strconv"

const _ChainHandledState_name = "ChainHandledStateThenFailedChainHandledStateElseFailedChainHandledStateUnhandledChainHandledStateThenChainHandledStateElse"

var _ChainHandledState_index = [...]uint8{0, 27, 54, 80, 101, 122}

func (i ChainHandledState) String() string {
	if i < 0 || i >= ChainHandledState(len(_ChainHandledState_index)-1) {
		return "ChainHandledState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChainHandledState_name[_ChainHandledState_index[i]:_ChainHandledState_index[i+1]]
}
